### ISSUE TITLE
1.20.1 Custom-head mobs not burning

### ISSUE THREAD

**Issue by piebaker** [Tschipcraft/more_mobs#6]
### Describe the bug

Custom-headed mobs are currently not burning in daylight. This is a duplicate of #3 , however it appears to be broken currently. This is using the mod version

### Steps to reproduce

Load more-mobs
Spawn zombies in the daylight
Custom-head zombies will not burn

### Expected behavior

Custom-head zombies will not burn

### Additional context

Having a setting for this would be great, with it defaulted to on

**Comment by Tschipcraft** [comment]
This feature is currently only in the GitHub repo and not yet distributed to GitHub releases, Modrinth, etc.
It will be in v1.5, even with the mentioned setting, stay tuned!

**Comment by piebaker** [comment]
Oh i see, i thought it had already been built out/released, my bad! 
Any idea of an ETA for that out of curiosity? (Some players of mine really want this feature!) 
Otherwise is there any way to build the datapack/mod out from the github repo ATM? 
From your modrinth pages you also build .jar's but i cant find a gradle.bat to build from for that

**Comment by Tschipcraft** [comment]
I plan on releasing it tomorrow actually.

Funny story, Modrinth actually inspired me to build the mod versions myself. 
A while back they added a package as mod button to their web ui, that automatically packages data packs into mods. Two months ago, I then started exploring this topic myself to add better metadata and a global settings menu across all worlds to my mods, so since this is a bit experimental, there's no build.gradle file. Right now, I just translate the Java files externally beforehand (from /src to /net).

I haven't updated the GitHub workflow yet, so you sadly can't build the data pack yourself right now.

**Comment by piebaker** [comment]
Oh sweet, not long then. 
Interesting that Modrinth even has that feature. Afaik the old converters on Github were archived due to some teething issues. Wonder how they got around it. 

I also managed to use the pack in its current form to test, just removed everything aside from the data folder, licences, etc. 
Then loaded like a regular datapack

Thanks for the quick responses, ill close this issue off now!
