### ISSUE TITLE
[More Mobs + Spawn Animations] Incompatible with Dungeons and Taverns Stronghold Rework

### ISSUE THREAD

**Issue by Deerhall** [Tschipcraft/more_mobs#9]
### Describe the bug

https://modrinth.com/datapack/dungeons-and-taverns-stronghold-rework/version/BBsnGqrp
Adding this mod to the server stops all functionality of both More Mobs + Spawn Animations.

### Steps to reproduce

Fabric server (fabric-server-mc.1.20.2-loader.0.14.24-launcher.0.11.2) adding Dungeons and Taverns Stronghold Rework
to the mods folder containing More Mobs and Spawn Animations. 

When running the server, no visual changes to monsters can be found (+ no spawn animations).
Running "/trigger tschipcraft.menu" or "/function #tschipcraft:menu" does not result in any chat output.

### Expected behavior

Simply, the stronghold overhaul mod should not break functionality of [More Mobs + Spawn Animations].

### Additional context

Problem is resolved when removing the Dungeons and Taverns mod.

**Comment by Tschipcraft** [comment]
Thank you for the bug report, however this is an issue with DnT Stronghold Rework, since it specifies a resource in the minecraft:tick tag that doesn't exist. Please let the creator of DnT know, since this might break or impair other data packs or mods as well.

Stack trace: `[19:02:21] [Render thread/ERROR]:
 Couldn't load tag minecraft:tick as it is missing following references: nova_structures:mobs (from fabric)`

**Comment by Tschipcraft** [comment]
This issue has been resolved as of DnT Stronghold Overhaul v1.1 🎉 ([see changelog](https://modrinth.com/datapack/dungeons-and-taverns-stronghold-rework/version/v1.1))
